# Generated by Django 2.0.3 on 2018-03-23 18:57

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Words_Room_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room')),
                ('words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Words')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/images/', storage=django.core.files.storage.FileSystemStorage(location='loci/uploads/'), upload_to='images'),
        ),
        migrations.AddField(
            model_name='room',
            name='text',
            field=models.ManyToManyField(to='rooms.Words'),
        ),
    ]
