# Generated by Django 2.0.3 on 2018-03-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20180323_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='ZjhXLzwIcf', max_length=500),
        ),
    ]
