# Generated by Django 2.0.3 on 2018-03-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Static_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=350)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='EgMKFysRkv', max_length=500),
        ),
    ]
