# Generated by Django 2.0.3 on 2018-03-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20180323_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='Tu9Md5v12G', max_length=500),
        ),
    ]
