# Generated by Django 2.0.3 on 2018-05-03 22:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/images/', storage=django.core.files.storage.FileSystemStorage(location='/home/jon/repos/memory_palace/loci/loci/uploads'), upload_to='images'),
        ),
        migrations.AlterField(
            model_name='room',
            name='images',
            field=models.ManyToManyField(blank=True, to='rooms.Image'),
        ),
        migrations.AlterField(
            model_name='room',
            name='text',
            field=models.ManyToManyField(blank=True, to='rooms.Words'),
        ),
    ]
