# Generated by Django 2.0.3 on 2018-05-03 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20180503_2254'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='words_room_style',
            unique_together={('room', 'words')},
        ),
    ]
