# Generated by Django 2.0.3 on 2018-05-04 02:13

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20180503_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_Room_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.FileField(default='settings.MEDIA_ROOT/images/', storage=django.core.files.storage.FileSystemStorage(location='/home/jon/repos/memory_palace/loci/loci/uploads'), upload_to='images')),
                ('background_image_format', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Marquee_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior', models.CharField(default='scroll', max_length=24)),
                ('direction', models.CharField(default='left', max_length=18)),
                ('image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Image')),
                ('words', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Words')),
            ],
        ),
        migrations.AddField(
            model_name='image_room_style',
            name='border_radius',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image_room_style',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image_room_style',
            name='marquee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image_room_style',
            name='opacity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='words_room_style',
            name='marquee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='words_room_style',
            name='size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='words_room_style',
            name='style',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='image_room_style',
            unique_together={('room', 'image')},
        ),
    ]
