# Generated by Django 2.0.3 on 2018-05-09 04:09

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_auto_20180509_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default='(1, 101)', validators=[django.contrib.postgres.validators.RangeMinValueValidator(1), django.contrib.postgres.validators.RangeMaxValueValidator(100)])),
                ('height', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default='(1,101)', validators=[django.contrib.postgres.validators.RangeMinValueValidator(1), django.contrib.postgres.validators.RangeMaxValueValidator(100)])),
                ('border_radius_tl', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default='(1,101)', validators=[django.contrib.postgres.validators.RangeMinValueValidator(1), django.contrib.postgres.validators.RangeMaxValueValidator(100)])),
                ('border_radius_tr', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default='(1,101)', validators=[django.contrib.postgres.validators.RangeMinValueValidator(1), django.contrib.postgres.validators.RangeMaxValueValidator(100)])),
                ('border_radius_bl', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default='(1,101)', validators=[django.contrib.postgres.validators.RangeMinValueValidator(1), django.contrib.postgres.validators.RangeMaxValueValidator(100)])),
                ('border_radius_br', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default='(1,101)', validators=[django.contrib.postgres.validators.RangeMinValueValidator(1), django.contrib.postgres.validators.RangeMaxValueValidator(100)])),
                ('opacity', django.contrib.postgres.fields.ranges.FloatRangeField(blank=True, default='(0.1, 1.1)', validators=[django.contrib.postgres.validators.RangeMinValueValidator(0.1), django.contrib.postgres.validators.RangeMaxValueValidator(1.1)])),
                ('marquee', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Words_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default='(0, 255)', validators=[django.contrib.postgres.validators.RangeMinValueValidator(0), django.contrib.postgres.validators.RangeMaxValueValidator(255)])),
                ('size', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default='(1, 10)', validators=[django.contrib.postgres.validators.RangeMinValueValidator(1), django.contrib.postgres.validators.RangeMaxValueValidator(10)])),
                ('style', models.CharField(default='', max_length=8)),
                ('marquee', models.BooleanField(default=False)),
                ('words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Words')),
            ],
        ),
    ]
