# Generated by Django 2.0.3 on 2018-05-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_image_style_words_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words_style',
            name='style',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
