# Generated by Django 2.0.3 on 2018-05-10 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_auto_20180510_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marquee_style',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Image'),
        ),
        migrations.AlterField(
            model_name='marquee_style',
            name='words',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Words'),
        ),
    ]
