# Generated by Django 2.0.3 on 2018-05-10 21:31

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_auto_20180510_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marquee_style',
            name='scrollamount',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default='(1, 5)', null=True, validators=[django.contrib.postgres.validators.RangeMinValueValidator(1), django.contrib.postgres.validators.RangeMaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='marquee_style',
            name='scrolldelay',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default='(1, 5)', null=True, validators=[django.contrib.postgres.validators.RangeMinValueValidator(1), django.contrib.postgres.validators.RangeMaxValueValidator(5)]),
        ),
    ]
