# Generated by Django 2.0.3 on 2018-05-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_auto_20180510_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_style',
            old_name='border_radius_bl',
            new_name='brads_bl_range',
        ),
        migrations.RenameField(
            model_name='image_style',
            old_name='border_radius_br',
            new_name='brads_br_range',
        ),
        migrations.RenameField(
            model_name='image_style',
            old_name='border_radius_tl',
            new_name='brads_tl_range',
        ),
        migrations.RenameField(
            model_name='image_style',
            old_name='border_radius_tr',
            new_name='brads_tr_range',
        ),
        migrations.RenameField(
            model_name='image_style',
            old_name='height',
            new_name='height_range',
        ),
        migrations.RenameField(
            model_name='image_style',
            old_name='opacity',
            new_name='opacity_range',
        ),
        migrations.RenameField(
            model_name='image_style',
            old_name='width',
            new_name='width_range',
        ),
        migrations.RenameField(
            model_name='words_style',
            old_name='color',
            new_name='color_range',
        ),
        migrations.RenameField(
            model_name='words_style',
            old_name='size',
            new_name='size_range',
        ),
        migrations.AddField(
            model_name='image_style',
            name='brads_bl',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='image_style',
            name='brads_tl',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='image_style',
            name='brads_tr',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='image_style',
            name='cur_height',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='image_style',
            name='cur_opacity',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='image_style',
            name='cur_width',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='words_style',
            name='cur_color',
            field=models.IntegerField(blank=True, default=255),
        ),
        migrations.AddField(
            model_name='words_style',
            name='cur_size',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
