# Generated by Django 2.0.3 on 2018-05-10 22:17

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_auto_20180510_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words_style',
            old_name='color_range',
            new_name='color_range_b',
        ),
        migrations.AddField(
            model_name='words_style',
            name='color_b_int',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='words_style',
            name='color_g_int',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='words_style',
            name='color_r_int',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='words_style',
            name='color_range_g',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default='(0, 255)', validators=[django.contrib.postgres.validators.RangeMinValueValidator(0), django.contrib.postgres.validators.RangeMaxValueValidator(255)]),
        ),
        migrations.AddField(
            model_name='words_style',
            name='color_range_r',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default='(0, 255)', validators=[django.contrib.postgres.validators.RangeMinValueValidator(0), django.contrib.postgres.validators.RangeMaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='words_style',
            name='cur_color',
            field=models.CharField(blank=True, default='black', max_length=7),
        ),
    ]
