# Generated by Django 2.0.3 on 2018-05-10 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_auto_20180510_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_style',
            old_name='cur_height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='image_style',
            old_name='cur_opacity',
            new_name='opacity',
        ),
        migrations.RenameField(
            model_name='image_style',
            old_name='cur_width',
            new_name='width',
        ),
        migrations.RenameField(
            model_name='words_style',
            old_name='cur_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='words_style',
            old_name='cur_size',
            new_name='size',
        ),
    ]
