# Generated by Django 2.0.3 on 2018-05-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0019_auto_20180510_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words_style',
            name='color',
            field=models.CharField(blank=True, default='255,255,255', max_length=13),
        ),
    ]
