# Generated by Django 2.0.3 on 2018-05-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0021_auto_20180510_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marquee_style',
            old_name='cur_scrollamount',
            new_name='scrollamount',
        ),
        migrations.RenameField(
            model_name='marquee_style',
            old_name='cur_scrolldelay',
            new_name='scrolldelay',
        ),
    ]
