# Generated by Django 2.0.3 on 2018-05-10 22:55

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0022_auto_20180510_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='marquee_style',
            name='scrollamount_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default='(1, 50)', null=True, validators=[django.contrib.postgres.validators.RangeMinValueValidator(1), django.contrib.postgres.validators.RangeMaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='marquee_style',
            name='scrolldelay_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, default='(1, 50)', null=True, validators=[django.contrib.postgres.validators.RangeMinValueValidator(1), django.contrib.postgres.validators.RangeMaxValueValidator(5)]),
        ),
    ]
